/* 230221 TUE */
/* 연습용 테이블 생성하기 */
SELECT * FROM DEPT;

CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT; -- DEPT테이블이 복제

SELECT * FROM DEPT_TEMP; 

DROP TABLE DEPT_TEMP; -- DEPT_TEMP 테이블 삭제

/* 테이블에 데이터를 추가하는 INSERT 문 */
/*
* INSERT INTO 테이블이름 (열1, 열2, ......) VALUES (열에 해당하는 데이터,......)
*/
/* 테이블에 데이터를 삽입(INSERT)하는 첫 번째 방법 : 테이블 목록과 추가 할 값을 모두 표기  */ 
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE', 'SEOUL');
-- 같은 값이 계속 해서 들어갈 수 있음 -> 제약조건을 걸어줘야함
DESC DEPT_TEMP;
DELETE FROM DEPT_TEMP
    WHERE DEPTNO = 50; -- 자료를 삭제
INSERT INTO DEPT_TEMP(LOC, DEPTNO) VALUES('BUSAN', 60); 

INSERT INTO DEPT_TEMP VALUES (70, 'DEVELOPER', 'SUWON'); -- 테이블 열을 안넣어 줘도 됨 ; 
INSERT INTO DEPT_TEMP VALUES ( 80, 'GUEST', 'INCHEON');

/* 테이블에 NULL데이터 입력하기 */
INSERT INTO DEPT_TEMP VALUES(90, 'WEB', NULL);
INSERT INTO DEPT_TEMP VALUES(91, 'MOBILE', '');
INSERT INTO DEPT_TEMP(DEPTNO, LOC) VALUES(92, 'ULSAN');

/* EMP TABLE만 복사 내용은 복사하지 않음 */
CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP
        WHERE 1 != 1; -- 테이블을 복사하면서 데이터는 복사하고 싶지 않을 때 사용

SELECT * FROM EMP_TEMP;
/* 날짜 데이터는 '2020/01/01', '2020-01-01' 입력 가능
* TO_DATE('2021/01/01', 'YYYY/MM/DD')
*/
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES(9001, '연쥬', '왕', NULL, '1990/03/17', 9900, 1000, 10);

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES(9002, '연쥬맘', '왕맘', NULL, '1964/09/10', 9900, 2000, 10);

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES(9003, '연쥬팝', '왕팝', NULL, '1961/04/26', 500, 10, 30);

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES(9004, '연쥬씻', '왕씻', 9002, '1992-12-14', 1000, 100, 20);
        
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
        VALUES(9005, '헤더', '왕자체', 9001, TO_DATE('1990/03/17', 'YYYY/MM/DD'), 1000, NULL, 40);
                    
-- COMMIT을해야함

/* 테이블에 있는 데이터 수정하기 */
/* UPDATE [변경할 테이블] 
* SET  [변경할 열....] = [변경할 데이터,.....]
* WHERE 조건절
*/

SELECT * FROM DEPT_TEMP;

UPDATE DEPT_TEMP SET LOC = 'SEOUL';

UPDATE DEPT_TEMP
    SET LOC = 'BUSAN'
    WHERE DNAME = 'WEB';

UPDATE DEPT_TEMP
    SET DNAME = 'ANDROID', LOC = 'DAEGU'
    WHERE DEPTNO = 60;
    
UPDATE DEPT_TEMP
    SET (DNAME, LOC) = (SELECT DNAME, LOC
                                FROM DEPT
                                WHERE DEPTNO = 40)
    WHERE DEPTNO = 40;
    
/* 테이블에 있는 데이터 삭제하기 (DELETE) */
CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2; -- 테이블 안의 데이터 전체 삭제
DROP TABLE EMP_TEMP2; -- 테이블 그 자체를 삭제

DELETE FROM EMP_TEMP2
    WHERE JOB = 'MANAGER';

-- 서브쿼리를 이용한 DELETE 
DELETE FROM EMP_TEMP2
    WHERE EMPNO IN (SELECT E.EMPNO
                        FROM EMP_TEMP2 E, SALGRADE S
                        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                        AND S.GRADE = 3
                        AND DEPTNO = 30);

/* 연습 문제 */
/* 이후 진행하는 문제는 다음 SQL문을 실행하여 EMP, DEPT, SALGRADE 테이블을 복사한 테이블로 진행
하세요. 다음 SQL문을 한 번에 한 문장씩 실행합니다. */

CREATE TABLE EX_EMP AS SELECT * FROM EMP;
CREATE TABLE EX_DEPT AS SELECT * FROM DEPT;
CREATE TABLE EX_SALGRADE AS SELECT * FROM SALGRADE;

-- 1. EX_DEPT 테이블에 50, 60, 70, 80을 등록하는 SQL문을 작성하세요.
INSERT INTO EX_DEPT(DEPTNO, DNAME, LOC)
    VALUES(50, 'ORACLE', 'BUSAN');
INSERT INTO EX_DEPT(DEPTNO, DNAME, LOC)
    VALUES(60, 'SQL', 'ILSAN');
INSERT INTO EX_DEPT(DEPTNO, DNAME, LOC)
    VALUES(70, 'SELECT', 'INCHEON');
INSERT INTO EX_DEPT(DEPTNO, DNAME, LOC)
    VALUES(80, 'DML', 'BUNDANG');

SELECT * FROM EX_DEPT;

-- 2. EX_EMP 테이블에 다음 8명의 사원정보를 등록하는 SQL문을 작성하세요.
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7201, 'TEST_USER1', 'MANAGER', 7788, '2016/01/02', 4500, NULL, 50);
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7202, 'TEST_USER2', 'CLERK', 7201, '2016/02/21', 1800, NULL, 50);
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7203, 'TEST_USER3', 'ANALYST', 7201, '2016/04/11', 3400, NULL, 60);
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7204, 'TEST_USER4', 'SALESMAN', 7201, '2016/05/31', 2700, 300, 60);
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7205, 'TEST_USER5', 'CLERK', 7201, '2016/07/20', 2600, NULL, 70);
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7206, 'TEST_USER6', 'CLERK', 7201, '2016/09/08', 2600, NULL, 70);
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7207, 'TEST_USER7', 'LECTURER', 7201, '2016/10/28', 2300, NULL, 80);
INSERT INTO EX_EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES(7208, 'TEST_USER8', 'STUDENT', 7201, '2018/03/09', 1200, NULL, 80);

-- 3. EX_EMP에 속한 사원 중 50번 부서에서 근무하는 사원들의 평균 급여보다 많은 급여를 받고있는 사원들을 70번 부서로 옮기는 SQL문을 작성하세요.
UPDATE EX_EMP
    SET DEPTNO = 70
    WHERE SAL > (SELECT AVG(SAL)
                    FROM EX_EMP
                    WHERE DEPTNO = 50);

SELECT * FROM EX_EMP;

-- 4. EX_EMP에 속한 사원 중, 60번 부서의 사원중에 입사일이 가장 빠른 사원보다 늦게 입사한 사원의 급여를 10%인상하고 80번 부서로 옮기는 SQL문을 작성하세요.
UPDATE EX_EMP
    SET DEPTNO = 80, SAL = SAL*1.1
    WHERE HIREDATE > (SELECT MIN(HIREDATE)
                        FROM EX_EMP
                        WHERE DEPTNO = 60);

-- 5. EX_EMP에 속한 사원 중, 급여 등급이 5인 사원을 삭제하는 SQL문을 작성하세요.
SELECT * FROM EX_SALGRADE;

DELETE FROM EX_EMP
    WHERE EMPNO IN (SELECT E.EMPNO
                        FROM EX_EMP E, EX_SALGRADE S
                        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                        AND S.GRADE = 5);
